title: Bodhayan Prasad
logo: /assets/img/ORCID.png
description: I'm a post-doctoral bioinformatician at the Wolfson Wohl Cancer Research Centre. I study metabolic pathways that are unique to Leukaemia, using different kinds of datasets, including single-cell levels. During my doctorate, I focused on personalized medicine for various diseases like rheumatoid arthritis, diabetes, CVD, cancer, and mental health. I also researched stratified healthcare, particularly for patients with multiple diseases. In addition to my computational work, I'm passionate about teaching. I've assisted my PhD supervisor in lectures and earned an Associate Fellowship at Higher Education (AFHEA) status.
show_downloads: false
google_analytics: G-XDTS8NJQKD
theme: jekyll-theme-minimal
